import Head from "next/head";

import { Header } from "../components/Header";
import { Banner } from "../components/Banner";
import { Nav } from "../components/Nav";
import { About } from "../components/About";
import { Service } from "../components/Service";
import { Work } from "../components/Work";
import { Contact } from "../components/Contact";

export default function Home() {
  return (
    <>
      <Head>
        <title>Santiago Segurado | Full Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-site bg-no-repeat bg-cover overflow-hidden">
        <Header />
        <Banner />
        <Nav />
        <About />
        <Service />
        <Work />
        <Contact />
        <div className='h-[4000px]'></div>
      </main>
    </>
  );
}
